// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsInfo.DbContexts;

#nullable disable

namespace ProductsInfo.Migrations
{
    [DbContext(typeof(ProductInfoContext))]
    partial class ProductInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("ProductsInfo.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kia Sportage 2020",
                            Price = 95000000m,
                            ProductType = "Vehiculos",
                            PurchaseDate = new DateTimeOffset(new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            State = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apartamento Chicó",
                            Price = 450000000m,
                            ProductType = "Apartamentos",
                            PurchaseDate = new DateTimeOffset(new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            State = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chevrolet Tracker 2022",
                            Price = 125000000m,
                            ProductType = "Vehiculos",
                            PurchaseDate = new DateTimeOffset(new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            State = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Casa Usaquen",
                            Price = 700000000m,
                            ProductType = "Apartamentos",
                            PurchaseDate = new DateTimeOffset(new DateTime(2005, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            State = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Anillo Oro",
                            Price = 1500000m,
                            ProductType = "Bienes",
                            PurchaseDate = new DateTimeOffset(new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            State = "Inactive"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lote Sogamoso, Boyacá",
                            Price = 110000000m,
                            ProductType = "Terrenos",
                            PurchaseDate = new DateTimeOffset(new DateTime(1998, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            State = "Active"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lote Moniquira, Boyaca",
                            Price = 90000000m,
                            ProductType = "Terrenos",
                            PurchaseDate = new DateTimeOffset(new DateTime(2013, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            State = "Active"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Reloj Rolex 1995",
                            Price = 12000000m,
                            ProductType = "Bienes",
                            PurchaseDate = new DateTimeOffset(new DateTime(1996, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            State = "Active"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Mazda 6 2008",
                            Price = 25000000m,
                            ProductType = "Vehiculos",
                            PurchaseDate = new DateTimeOffset(new DateTime(2007, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            State = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
