using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProductsInfo.Entities
{
    /// <summary>
    /// Ebtity Product
    /// </summary>
    public class Product
    {
        /// <summary>
        /// Ptoduct Id - Autogenerated
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Product description
        /// </summary>
        [MaxLength(200)]
        public string? Description { get; set; }

        /// <summary>
        /// Product Type
        /// </summary>
        [Required]
        [MaxLength(30)]
        public ProductType ProductType { get; set; }

        /// <summary>
        /// Price of the product
        /// </summary>
        [Required]
        public decimal Price { get; set; }

        /// <summary>
        /// Purchase date of the product
        /// </summary>
        public DateTimeOffset PurchaseDate { get; set; }

        /// <summary>
        /// Product State
        /// </summary>
        [Required]
        [MaxLength(30)]
        public ProductState State { get; set; }

    }

    /// <summary>
    /// Enum for the product type
    /// </summary>
    public enum ProductType
    {
        /// <summary>
        /// Bienes
        /// </summary>
        Bienes = 0,

        /// <summary>
        /// Vehiculos
        /// </summary>
        Vehiculos = 1,

        /// <summary>
        /// Terrenos
        /// </summary>
        Terrenos = 2,

        /// <summary>
        /// Apartamentos
        /// </summary>
        Apartamentos = 3
    }

    /// <summary>
    /// Enum for the product state
    /// </summary>
    public enum ProductState
    { 
        /// <summary>
        /// Active
        /// </summary>
        Active = 0,
        /// <summary>
        /// Inactive
        /// </summary>
        Inactive = 1,
    }
}
